apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kbtech-org-wildcard
  namespace: default
spec:
  secretName: kbtech-org-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - kbtech.org
    - "*.kbtech.org"