---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-cloudflare-secret
  namespace: networking
spec:
  encryptedData:
    CF_API_TOKEN: AgAihumPwgUKO4Os2w2m1m2wNXc1YlowDOV+uXOb6G0tMqIMnBXK9PCHcufX1Yqo8cTpfwtcw4kiagXMyMePNnneM1fCMnZn2fKKk9n0MhBCjxT+JtN4pilJrudleHEVGOmwcMAI52isMhEC4LseVmh8U4GWqsDyJMyjoJezdKoixHBbC1rm6asRlMmodcQ+7FL4k+ku+4NRv18ll3NjOl6UjsaP8AmMuez4aAhaafIa65JXIJ0vXnvpY0xC2z2tac5euW7G41kI7BXXOZreif6hpa51gjDHUEP070m3JQ+59u6r57Z3bzvyzr/Za+s6pjSZA3HioThEbdwWln6+c1XLlSzyJHrcx3/1c9mF8LWB4WTBZvKcyxI2iXDBJz5GVJ+sOfcUR4SwvOVAH33EKfCZ3dSbbw/D7Pzr4S8TjvJe4jBfiM0B4gw23JxR+Jf3rYlvfXNMxwOTXTudiJHeXNDV5a90JGRvl5QLmTlwM/5jKZrYcPR80LmdIY6dJ1QzBBOYJT02f7zGxtunzhKv9mlOw9mI1lY/YgBptwIwLEe4kEL8iHIjcZwhoQu8iJCXtgXpAFZiWA/nE4egnnPh9k9k0dNO/FlR01R3FmrLjLKo+dS2gZjgdl76K02phduvGh7v7nz2uO+wMy5g/NWWRJ8SjBEcrLYbB6UBet2OulEL52PmapDpY5xl03JhNDNxjYh7hCDtx/OqoxyXJvCuq1BNOuQUYfgzd1hJ5In+DrzOq/BermeR6hlp9skX3UXIsIISZjwGXA==
  template:
    metadata:
      name: external-dns-cloudflare-secret
      namespace: networking
