apiVersion: v1
data:
  CF_API_TOKEN: Y2Z1dF92dzR6bW9KM1V3WGVQMU9aRmJlcUU4a2FDcVRkTkFBM25JTzd3OVdqMDkyZWZiMjg=
kind: Secret
metadata:
  creationTimestamp: null
  name: external-dns-cloudflare-secret
  namespace: networking
