apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: tools
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: kbtech-fleet-clusters-local
    meta.helm.sh/release-namespace: default
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
