---
- name: Install Portainer stack
  hosts: dockerSwarm-01
  gather_facts: true
  become: true

  tasks:
    - name: Pull Portainer image
      command: docker pull portainer/portainer

    - name: Create Portainer data volume
      command: docker volume create portainer_data

    - name: Deploy Portainer as a service
      command: docker service create --name=portainer \
               --publish=9000:9000 \
               --constraint=node.role==manager \
               --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
               --mount=type=bind,src=/mnt/docker-data,dst=/data \
               portainer/portainer
