---
- name: Deploy Nginx Proxy Manager
  hosts: managers
  become: true
  tasks:
    - name: Pull Nginx Proxy Manager image
      docker_image:
        name: jc21/nginx-proxy-manager:latest
        source: pull
      register: nginx_proxy_manager_image

    - name: Create Docker network
      docker_network:
        name: nginx_proxy_manager_network

    - name: Deploy Nginx Proxy Manager service
      docker_service:
        name: nginx_proxy_manager
        image: jc21/nginx-proxy-manager:latest
        state: started
        published_ports:
          - "80:80"
          - "443:443"
          - "81:81"
        env:
          DB_MYSQL_HOST: 'mysql'
          DB_MYSQL_PORT: '3306'
          DB_MYSQL_USER: 'npm'
          DB_MYSQL_PASSWORD: 'npm'
          DB_MYSQL_NAME: 'npm'
        networks:
          - name: nginx_proxy_manager_network

    - name: Wait for service to stabilize
      wait_for:
        timeout: 300
        host: "{{ ansible_host }}"
        port: 81
      become: false
      delegate_to: localhost


- name: Install Portainer stack
  hosts: managers
  gather_facts: true
  become: true

  tasks:
    - name: Pull Portainer image
      command: docker pull portainer/portainer

    - name: Create Portainer data volume
      command: docker volume create portainer_data

    - name: Deploy Portainer as a service
      command: docker service create --name=portainer --publish=9000:9000 --constraint=node.role==manager --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock --mount=type=volume,src=portainer_data,dst=/data portainer/portainer
