- name: Remove pve-enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    state: absent
    update_cache: false

- name: Add pve-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
    update_cache: false

- name: Remove ceph-quincy enterprize subscription repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    state: absent
    update_cache: false

- name: Add ceph-quincy no-suscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present


    