---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Start and Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'

- name: Install Docker on RedHat-based systems
  package:
    name: docker
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Start and Enable Docker service on RedHat-based systems
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Initialize the Swarm
  command: docker swarm init
  register: swarm_init_output
  changed_when: "'Error' not in swarm_init_output.stderr"
  ignore_errors: yes

- name: Retrieve Swarm join token for worker nodes
  command: docker swarm join-token worker -q
  register: swarm_join_worker_token
  changed_when: false
  when: swarm_init_output.rc == 0

- name: Retrieve Swarm join token for manager nodes
  command: docker swarm join-token manager -q
  register: swarm_join_manager_token
  changed_when: false
  when: swarm_init_output.rc == 0

- name: Register manager and worker nodes
  add_host:
    name: "{{ item }}"
    groups: "swarm_{{ item.split()[0] }}"
    ansible_user: "{{ remote_user }}"
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
  with_items:
    - "{{ swarm_join_manager_token.stdout }}"
    - "{{ swarm_join_worker_token.stdout }}"
  when: swarm_init_output.rc == 0
