---
- name: check disk space
  hosts: "ubuntu, docker, k3s, pihole"
  vars:
    disk_alert_threshold: 80
  tasks:
    - name: get disk usage
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    - name: Send notification via Rocket.Chat
      uri:
        url: "{{ rocketchat_alert_webhook_url }}"
        method: POST
        body_format: json
        body:
          channel: "{{ rocketchat_alert_channel }}"
          username: "{{ rocketchat_alert_username }}"
          icon_emoji: ":warning:"
          text: "Disk space on {{ inventory_hostname }} is above {{ disk_alert_threshold }}%! (Used: {{ disk_usage.stdout }})"
        status_code:
          - 200
          - 201
          - 202
      no_log: true
      when: disk_usage.stdout | regex_replace('%', '') | int > disk_alert_threshold
