---
- name: Setup Docker Swarm with Portainer
  hosts: dockerswarm
  become: true
  vars:
    docker_users: ["{{ ansible_user }}"]
    ceph_mount: "/mnt/cephfs"
    portainer_data: "{{ ceph_mount }}/portainer_data"
  tasks:
    - name: Install required packages
      package:
        name: ["docker", "docker-compose", "python3-pip"]
        state: present
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Add users to the Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ docker_users }}"

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Portainer volume on shared storage
      file:
        path: "{{ portainer_data }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      run_once: true


    - name: Deploy Portainer as a Swarm service
      command: >
        docker service create \
        --name portainer \
        --publish 9000:9000 \
        --constraint 'node.role == manager' \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
        --mount type=bind,src={{ portainer_data }},dst=/data \
      run_once: true
