---

- name: Install and Configure Node Exporter

  hosts: test

  become: yes  # Use sudo to execute commands as root



  tasks:

    - name: Update APT cache

      apt:

        update_cache: yes



    - name: Install Node Exporter

      apt:

        name: prometheus-node-exporter

        state: present


    - name: Restart Node Exporter

      systemd:

        name: node_exporter

        state: restarted

      notify: Reload firewall rules

      notify: Update Prometheus configuration



    - name: Reload firewall rules

      meta: flush_handlers



- name: Update Prometheus Configuration

  hosts: 192.168.2.213

  become: yes



  tasks:

    - name: Add Node Exporter target to Prometheus configuration

      lineinfile:

        path: /etc/prometheus/prometheus.yml  # Adjust the path as needed

        line: "  - targets: ['{{ ansible_host }}:9100']"

        insertafter: '^    - job_name: node_exporter'



    - name: Restart Prometheus

      systemd:

        name: prometheus

        state: restarted

