---
- name: Mount Drives on Ubuntu Server
  hosts: docker
  become: yes
  tasks:
    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /mnt/data
        - /mnt/data2

    - name: Format /dev/sdb with ext4 filesystem (if needed)
      command: mkfs.ext4 /dev/sdb
      when: "'/mnt/data2' not in ansible_mounts | map(attribute='mount') | list"

    - name: Format /dev/sdc with ext4 filesystem (if needed)
      command: mkfs.ext4 /dev/sdc
      when: "'/mnt/data' not in ansible_mounts | map(attribute='mount') | list"

    - name: Mount /dev/sdb to /mnt/data2
      mount:
        path: /mnt/data2
        src: /dev/sdc
        fstype: ext4
        state: mounted
      when: "'/mnt/data2' not in ansible_mounts | map(attribute='mount') | list"

    - name: Mount /dev/sdc to /mnt/data
      mount:
        path: /mnt/data
        src: /dev/sdb
        fstype: ext4
        state: mounted
      when: "'/mnt/data' not in ansible_mounts | map(attribute='mount') | list"
