---
- name: Mount Drives on Ubuntu Server
  hosts: docker
  become: yes
  tasks:
    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /mnt/data
        - /mnt/data2

    - name: Mount /dev/sdb to /mnt/data2
      mount:
        path: /mnt/data2
        src: /dev/sdb
        fstype: ext4  # Replace with the appropriate filesystem type if needed
        state: mounted
      when: "'/mnt/data2' not in ansible_mounts | map(attribute='mount') | list"

    - name: Mount /dev/sdc to /mnt/data
      mount:
        path: /mnt/data
        src: /dev/sdc
        fstype: ext4  # Replace with the appropriate filesystem type if needed
        state: mounted
      when: "'/mnt/data' not in ansible_mounts | map(attribute='mount') | list"
