---
- hosts: netbox
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
        - python3-pip
        - python3-venv
        - libxml2-dev
        - libxslt1-dev
        - libffi-dev
        - libpq-dev
        - libssl-dev
        - libjpeg-turbo8-dev
        - zlib1g-dev

    - name: Clone NetBox repository
      git:
        repo: https://github.com/netbox-community/netbox.git
        dest: /opt/netbox
        update: yes

    - name: Create Python virtual environment
      command: python3 -m venv /opt/netbox/venv

    - name: Install required Python packages
      pip:
        requirements: /opt/netbox/requirements.txt
        virtualenv: /opt/netbox/venv

    - name: Create NetBox configuration file
      template:
        src: /opt/netbox/netbox/netbox/configuration.example.py
        dest: /opt/netbox/netbox/netbox/configuration.py
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Apply database migrations
      command: /opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py migrate --noinput

    - name: Create superuser (admin) account
      command: /opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py createsuperuser --noinput
