---
- name: 'Configure Proxmox hosts and prep for Ansible automation'
  hosts: 'proxmox'
  gather_facts: true
  tasks:
    - name: 'Ensure enterprise repo file is not present'
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
    - name: 'Switch to community repos'
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
        filename: pve-no-subscription
        state: 'present'

