---
- name: Fix Mixed Repository Suites and Remove NVIDIA Repository
  hosts: proxmox
  become: true

  tasks:
    - name: Ensure Proxmox and Debian repositories use the same base suite
      block:
        - name: Update /etc/apt/sources.list
          replace:
            path: /etc/apt/sources.list
            regexp: '^deb.*bullseye'
            replace: 'deb http://deb.debian.org/debian bullseye main contrib non-free'

        - name: Update /etc/apt/sources.list.d/download_proxmox_com_debian_pve.list
          replace:
            path: /etc/apt/sources.list.d/download_proxmox_com_debian_pve.list
            regexp: '^deb.*buster'
            replace: 'deb http://download.proxmox.com/debian/pve buster pve-no-subscription'

    - name: Update APT cache
      apt:
        update_cache: yes
      become_user: root

