---
- name: Copy SSH keys to remote servers
  hosts: "proxmox"
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Ensure SSH directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'
      become: yes

    - name: Copy public key to remote server
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      become: yes
