---
- hosts: "control, ubuntu, pihole, proxmox, docker , wazuh"
  become: yes
  tasks:
    - name: Ensure dpkg is configured
      shell: dpkg --configure -a
      ignore_errors: yes
      
    - name: Run apt commands
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: 'yes'

    - name: Run do-release-upgrade
      shell: do-release-upgrade -y
      async: 1200
      poll: 0
