---
default_linux_user: kurt
default_ssh_password: "{{ vault_default_ssh_pass }}"
default_sudo_password: "{{ vault_default_sudo_pass }}"

grafana_admin_user: admin
grafana_admin_password: "{{ vault_grafana_admin_password }}"

k3s_cluster_token: "{{ vault_k3s_cluster_token }}"

pihole_keepalived_auth_pass: "{{ vault_pihole_keepalived_auth_pass }}"
pihole_web_password: "{{ vault_pihole_web_password }}"

rocketchat_alert_webhook_url: "https://chat.kbtech.org/hooks/6a1a39575e4d1d1534a099b6/t5Cwbo8vccmQzmKjNwNz9QmcxE5BJoxKnsuma8KCsmCcGxBx"
rocketchat_alert_channel: "#alerts"
rocketchat_alert_username: "Ansible"
rocketchat_ansible_webhook_url: "https://chat.kbtech.org/hooks/6a1a38975e4d1d1534a099a2/fotj4pMYY6JweCsKS8YxcjYkRGHvDNH5N6NWNPDakvRHRuKM"
