---
linuxrmm_install_dir: "/opt/linuxrmm"
linuxrmm_script_url: "https://raw.githubusercontent.com/netvolt/LinuxRMM-Script/main/rmmagent-linux.sh"
linuxrmm_script_path: "{{ linuxrmm_install_dir }}/rmmagent-linux.sh"

rmm_arch: "amd64"
mesh_url: "https://mesh.kbtech.org/meshagents?script=1"
api_url: "https://api.kbtech.org"
param_4: "1"
param_5: "1"
auth_key: "8923ed3da5eaceb9c264b8d50ca34c8ae9f38bbd25b4630c87ec88ea390030fa"
device_name: "{{ inventory_hostname }}"

rmm_installed_check: "/usr/local/bin/rmmagent"

# Normal run:
# false = only install if missing, then make sure services are running
# true  = stop/kill/remove/reinstall agent
linuxrmm_force_reinstall: false

linuxrmm_required_packages:
  - curl
  - wget
  - ca-certificates
  - sudo

linuxrmm_services:
  - rmmagent
  - meshagent