---
    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest
  
    - name: Update Windows
      when: ansible_facts['os_family'] == 'Windows'
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed