---
- name: Install NFS utilities (RedHat-based)
  yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Install NFS utilities (Debian-based)
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure mount points exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items: "{{ nfsmounts }}"

- name: Mount NFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: defaults,nfsvers=4
    state: mounted
  with_items: "{{ nfsmounts }}"
