- name: Update Ubuntu
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600  # Update cache if older than 1 hour