# Create a directory to download RKE2 binary to
- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: '0755'

# Download the RKE2 binary
- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: https://github.com/rancher/rke2/releases/download/v1.27.7+rke2r1/rke2.linux-amd64
    dest: "{{ rke2_install_dir }}/rke2"
    mode: '0755'

# Set permissions on the RKE2 binary
- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/rke2"
    mode: '0755'
    state: file
