---
- name: Clean up Docker, GlusterFS, and Portainer
  hosts: "docker"
  gather_facts: false
  become: true

  tasks:
    - name: Remove Portainer service (if exists)
      command: docker service rm portainer
      ignore_errors: true

    - name: Stop and Disable Docker service
      service:
        name: docker
        state: stopped
        enabled: no

    - name: Uninstall Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Remove Docker data directory
      file:
        path: /var/lib/docker
        state: absent

    - name: Remove Docker daemon.json
      file:
        path: /etc/docker/daemon.json
        state: absent