---
- name: Setup Docker Swarm with Portainer
  hosts: docker
  become: true
  vars:
    docker_users: ["{{ ansible_user }}"]
    ceph_mount: "/mnt/cephfs"
    portainer_data: "{{ ceph_mount }}/portainer_data"
  tasks:
    - name: Install required packages
      package:
        name: ["docker", "docker-compose", "python3-pip"]
        state: present
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Add users to the Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ docker_users }}"

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Docker Swarm on manager
      command: "docker swarm init --advertise-addr {{ ansible_host }}"
      run_once: true
      when: inventory_hostname == swarm_manager
      register: swarm_init
      changed_when: "swarm_init.rc == 0"

    - name: Get Swarm join token for managers
      command: "docker swarm join-token -q manager"
      when: inventory_hostname == swarm_manager
      register: manager_token
      changed_when: false

  #  - name: Get Swarm join token for workers
   #   command: "docker swarm join-token -q worker"
    #  when: inventory_hostname == swarm_manager
     # register: worker_token
      #changed_when: false

    - name: Join manager nodes to Swarm
      command: "docker swarm join --token {{ manager_token.stdout }} {{ swarm_manager }}:2377"
      when: inventory_hostname != swarm_manager and inventory_hostname in groups['managers']

    #- name: Join worker nodes to Swarm
     # command: "docker swarm join --token {{ worker_token.stdout }} {{ swarm_manager }}:2377"
      #when: inventory_hostname in groups['workers']

    - name: Create Portainer volume on shared storage
      file:
        path: "{{ portainer_data }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      run_once: true


    - name: Deploy Portainer as a Swarm service
      command: >
        docker service create \
        --name portainer \
        --publish 9000:9000 \
        --constraint 'node.role == manager' \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
        --mount type=bind,src={{ portainer_data }},dst=/data \
        portainer/portainer-ce --admin-password "$(openssl rand -base64 16)"
      run_once: true
