---
- name: Install and Configure Grafana
  hosts: grafanaservers
  become: yes
  tasks:

    - name: Create a Grafana data source using API
      uri:
        url: http://localhost:3000/api/datasources
        method: POST
        user: admin
        password: steven87
        body: "{
          \"name\": \"Prometheus\",
          \"type\": \"prometheus\",
          \"url\": \"http://localhost:9090\",
          \"access\": \"proxy\",
          \"isDefault\": true
        }"
        status_code: 200

