---
- name: Install and configure Keepalived on 3 nodes
  hosts: dockerswarm
  become: true
  vars:
    virtual_ip: "192.168.201.20"
    interface: "eth0"
    priority:
      node1: 150
      node2: 100
      node3: 50
  tasks:
    - name: Install Keepalived
      package:
        name: keepalived
        state: present

    - name: Configure Keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"
      notify: Restart Keepalived

    - name: Enable and start Keepalived service
      service:
        name: keepalived
        state: started
        enabled: yes

  handlers:
    - name: Restart Keepalived
      service:
        name: keepalived
        state: restarted
