---
- import_playbook: task/gitsync.yml
- import_playbook: task/update.yml
#- import_playbook: task/proxmox.yml
- import_playbook: task/qemu-guest-agent.yml
- import_playbook: task/packages.yml
- import_playbook: task/pihole-update.yml
- import_playbook: task/chocolatey.yml
- import_playbook: task/ServerUpdate.yml
- import_playbook: task/choco.yml
- import_playbook: task/reboot.yml

