- name: manage ubuntu servers
  hosts: ubuntu
  become: yes
  gather_facts: true
  tasks:
    - import_role:
        name: manageservers/ubuntu

- name: manage pihole servers
  hosts: pihole
  become: yes
  gather_facts: true
  tasks:
    - import_role:
        name: manageservers/PiHole

- name: manage pihole servers
  hosts: proxmox
  become: yes
  gather_facts: true
  tasks:
    - import_role:
        name: manageservers/proxmox/update

- import_playbook: task/wazuhagent.yml