---
- name: Configure NTP Server
  hosts: ntpserver
  become: true

  tasks:
    - name: Install NTP Package
      apt:
        name: ntp
        state: present

    - name: Configure NTP Service
      copy:
        src: files/ntp.conf
        dest: /etc/ntp.conf
      notify: restart ntp

  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted
