- name: Setup Pi-hole HA
  hosts: pihole-ha
  become: yes

  vars:
    primary_server_ip: 192.168.200.3
    secondary_server_ip: 192.168.200.4
    vip_address: 192.168.200.2

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - jq

    - name: Configure primary Pi-hole server
      command: curl -sSL https://install.pi-hole.net | sudo bash /dev/stdin --reconfigure --dns 127.0.0.1

    - name: Retrieve secondary Pi-hole server token
      command: curl -sSL 'https://install.pi-hole.net' | sudo bash /dev/stdin --reconfigure --dns 127.0.0.1 | jq -r '.setupVars.webpassword'

      register: secondary_server_token

    - name: Configure secondary Pi-hole server
      command: >
        curl -sSL https://install.pi-hole.net | sudo bash /dev/stdin --reconfigure --dns 127.0.0.1 --upstream-dns "{{ primary_server_ip }}"
      when: secondary_server_token.stdout is defined

    - name: Configure primary Pi-hole as DHCP server
      lineinfile:
        path: /etc/pihole/setupVars.conf
        regex: '^DHCP_ACTIVE='
        line: 'DHCP_ACTIVE=true'

    - name: Add secondary DNS server to primary Pi-hole
      lineinfile:
        path: /etc/pihole/setupVars.conf
        regex: '^PIHOLE_DNS_1='
        line: 'PIHOLE_DNS_1={{ secondary_server_ip }}'

    - name: Configure VIP address
      lineinfile:
        path: /etc/pihole/setupVars.conf
        regex: '^IPV4_ADDRESS='
        line: 'IPV4_ADDRESS={{ vip_address }}'

    - name: Restart Pi-hole service
      service:
        name: pihole-FTL
        state: restarted
