- name: Install Portainer stack
  hosts: docker-01
  gather_facts: false
  become: true
  tasks:
    - name: Pull Portainer image
      command: docker pull portainer/portainer-ce:latest

    - name: Ensure Portainer data directory exists on CephFS
      file:
        path: /mnt/cephfs/portaier_data
        state: directory
        mode: '0777'

    - name: Deploy Portainer as a service
      command: >
        docker service create --name=portainer
        --publish=9000:9000
        --constraint=node.role==manager
        --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock
        --mount=type=bind,src=/mnt/cephfs/portaier_data,dst=/data
        portainer/portainer-ce:latest
