---
- name: Install Portainer stack
  hosts: docker-01
  gather_facts: false
  become: true
  tasks:
    - name: Pull Portainer image
      command: docker pull portainer/portainer

    - name: Create Portainer data volume
      command: docker volume create portainer_data

    - name: Deploy Portainer as a service
      command: docker service create --name=portainer --publish=9443:9443 --constraint=node.role==manager --mount=type=bind,src=/mnt/var/run/docker.sock,dst=/var/run/docker.sock --mount=type=volume,src=portainer_data,dst=/mnt/data portainer/portainer
