- name: proxmox_cloudinit.yml
  hosts: PROXMOX-01
  gather_facts: true
  vars_prompt: 
  - name: "ansible_password"
    prompt: "Enter the remote password"
    private: yes
  vars: 
    ansible_user: root
  tasks:
  - import_role: 
      name: proxmox/cloud-init