---
- name: 'Configure Proxmox hosts and prep for Ansible automation'
  hosts: 'proxmox'
  gather_facts: true
  vars:
    packages:
      - 'python-pip'
      - 'python-dev'
      - 'build-essential'
      - 'mdadm'
      - 'cifs-utils'
  tasks:
    - name: 'Ensure enterprise repo file is not present'
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
    - name: 'Switch to community repos'
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve buster pve-no-subscription'
        state: 'present'
    - name: 'Enable nested virtualization'
      template:
        src: "templates/intel_nested_virtualization"
        dest: /etc/modprobe.d/kvm-intel.conf  
      register: nested_virt_require_reboot
    - name: 'Install python-apt so native apt plugins work'
      package:
        name: 'python-apt'
        state: 'present'
    - name: 'Update all packages to the latest version'
      apt:
        upgrade: 'dist'
    - name: 'Install pip packages'
      apt:
        name: "{{ packages }}"
    - name: 'Pip update pip'
      pip:
        name: 'pip'
        state: 'latest'
