- name: Upgrade Proxmox nodes one at a time
  hosts: proxmox
  gather_facts: false
  become: true

  # serial: 1  # Ensures updates happen one node at a time
  vars:
    use_enterprise_repos: false
  roles:
    - update_proxmox
 
