- name: Upgrade Proxmox nodes one at a time
  hosts: pve-dev
  serial: 1  # Ensures updates happen one node at a time
  vars:
    use_enterprise_repos: false
  roles:
    - proxmox_newsetup
    - ironicbadger.proxmox_nag_removal
