- name: install latest qemu-guest-agent
  hosts: "control, ubuntu, pihole, proxmox, ntp-server"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true