---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Run gitsync playbook
      import_playbook: task/gitsync.yml
      register: gitsync_result

    - name: Send gitsync playbook output to Rocket.Chat
      when: gitsync_result is defined
      rocketchat:
        token: 64d84e3a7d3522bf44894dc0/HsoR2gS7bjDjzjKk8BNuQiKzQJCBTenj7aDKCSZFmPuC8zNh
        domain: rocketchat.kbtech.org
        msg: "GitSync Playbook Output:\n{{ gitsync_result.stdout }}"
        channel: "Ansible"

    - name: Run update playbook
      import_playbook: task/update.yml
      register: update_result

    - name: Send update playbook output to Rocket.Chat
      when: update_result is defined
      rocketchat:
        token: 64d84e3a7d3522bf44894dc0/HsoR2gS7bjDjzjKk8BNuQiKzQJCBTenj7aDKCSZFmPuC8zNh
        domain: rocketchat.kbtech.org
        msg: "Update Playbook Output:\n{{ update_result.stdout }}"
        channel: "Ansible"

    # Repeat the above pattern for each playbook you want to run and send output for.
