---
  tasks:
    - name: Run gitsync playbook
      include_playbook: task/gitsync.yml
      register: gitsync_output

    - name: Run update playbook
      include_playbook: task/update.yml
      register: update_output

    - name: Run proxmox playbook
      include_playbook: task/proxmox.yml
      register: proxmox_output

    - name: Run qemu-guest-agent playbook
      include_playbook: task/qemu-guest-agent.yml
      register: qemu_guest_agent_output

    - name: Run packages playbook
      include_playbook: task/packages.yml
      register: packages_output

    - name: Run pihole-update playbook
      include_playbook: task/pihole-update.yml
      register: pihole_update_output

    - name: Run chocolatey playbook
      include_playbook: task/chocolatey.yml
      register: chocolatey_output

    - name: Run ServerUpdate playbook
      include_playbook: task/ServerUpdate.yml
      register: server_update_output

    - name: Run choco playbook
      include_playbook: task/choco.yml
      register: choco_output

    - name: Run reboot playbook
      include_playbook: task/reboot.yml
      register: reboot_output

- name: Send Ansible output to Rocket.Chat
  community.general.rocket_chat:
    msg: |
      Ansible Playbooks Execution Summary:
      
      GitSync Playbook Output:
      {{ gitsync_output.stdout }}
      
      Update Playbook Output:
      {{ update_output.stdout }}
      
      Proxmox Playbook Output:
      {{ proxmox_output.stdout }}
      
      QEMU Guest Agent Playbook Output:
      {{ qemu_guest_agent_output.stdout }}
      
      Packages Playbook Output:
      {{ packages_output.stdout }}
      
      Pi-hole Update Playbook Output:
      {{ pihole_update_output.stdout }}
      
      Chocolatey Playbook Output:
      {{ chocolatey_output.stdout }}
      
      ServerUpdate Playbook Output:
      {{ server_update_output.stdout }}
      
      Choco Playbook Output:
      {{ choco_output.stdout }}
      
      Reboot Playbook Output:
      {{ reboot_output.stdout }}
   token: 64d84e3a7d3522bf44894dc0/HsoR2gS7bjDjzjKk8BNuQiKzQJCBTenj7aDKCSZFmPuC8zNh
        domain: rocketchat.kbtech.org
  delegate_to: localhost
