- hosts: "control, ubuntu, pihole, proxmox, ntpserver"
  become: yes
  tasks:
    - name: apt
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: 'yes'