---
- name: Install Wazuh Manager and Dashboard on a Single Server
  hosts: wazuh_server
  become: true
  vars:
    wazuh_version: "4.7.3"

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - lsb-release
          - gnupg
          - unzip
        state: present
        update_cache: yes

    - name: Add Wazuh repository key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/{{ wazuh_version }}/apt/ stable main"
        state: present
        filename: wazuh

    - name: Install Wazuh Manager
      apt:
        name: wazuh-manager
        state: present

    - name: Enable and start Wazuh Manager service
      systemd:
        name: wazuh-manager
        enabled: yes
        state: started

    - name: Install OpenSearch
      apt:
        name: opensearch
        state: present

    - name: Enable and start OpenSearch service
      systemd:
        name: opensearch
        enabled: yes
        state: started

    - name: Install Wazuh Dashboard (Kibana with Wazuh Plugin)
      apt:
        name: wazuh-dashboard
        state: present

    - name: Enable and start Wazuh Dashboard service
      systemd:
        name: wazuh-dashboard
        enabled: yes
        state: started

    - name: Allow Wazuh API (TCP 55000) through firewall
      ufw:
        rule: allow
        port: "55000"
        proto: tcp

    - name: Allow Wazuh agent communication (TCP 1514, 1515)
      ufw:
        rule: allow
        port: "1514:1515"
        proto: tcp

    - name: Allow Wazuh Dashboard access (TCP 5601)
      ufw:
        rule: allow
        port: "5601"
        proto: tcp

    - name: Reload UFW to apply rules
      command: ufw reload
      changed_when: false
