---
all:
  children:
    k3s_servers:
      hosts:
        k3s-c1:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_c1 }}"
        k3s-c2:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_c2 }}"
        k3s-c3:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_c3 }}"
    k3s_agents:
      hosts:
        k3s-w1:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_w1 }}"
        k3s-w2:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_w2 }}"
        k3s-w3:
          ansible_host: "{{ k3s_node_network }}.{{ k3s_node_ip_suffixes.k3s_w3 }}"
    k3s_cluster:
      children:
        k3s_servers:
        k3s_agents:
