[k3s_servers]
k3s-c1 ansible_host=192.168.201.31
k3s-c2 ansible_host=192.168.201.32
k3s-c3 ansible_host=192.168.201.33

[k3s_agents]
k3s-w1 ansible_host=192.168.201.34
k3s-w2 ansible_host=192.168.201.35
k3s-w3 ansible_host=192.168.201.36

[k3s_cluster:children]
k3s_servers
k3s_agents

[k3s_cluster:vars]
ansible_user=kurt
k3s_install_script=/tmp/k3s-install.sh
k3s_server_args=--write-kubeconfig-mode=644
k3s_agent_args=
