---
- name: Run apt commands
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: 'yes'

- name: Run do-release-upgrade
  shell: do-release-upgrade
  async: 1200
  poll: 0



