- name: Update Ubuntu
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600  # Update cache if older than 1 hour

- name: Ensure update-manager-core is installed
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.apt:
    name: update-manager-core
    state: present
    
- name: Ensure release-upgrades is set to LTS
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/update-manager/release-upgrades
    regexp: '^Prompt='
    line: 'Prompt=lts'
    create: true  # In case the file does not exist
    backup: true  # Keep a backup before modifying

- name: Upgrade to the next Ubuntu release
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.command: do-release-upgrade -f DistUpgradeViewNonInteractive
  register: upgrade_output
  changed_when: "'No new release found' not in upgrade_output.stdout"







